server:
  port: 8087


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka #默认注册中心地址
  instance:
    lease-renewal-interval-in-seconds: 1     #表示eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，
    #server端没有收到client的心跳，则将摘除该instance
    lease-expiration-duration-in-seconds: 2 #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，
    #在这个时间内若没收到下一次心跳，则将移除该instance

spring:
  application:
    name: front-pay-provider #应用名称  保证唯一   一般采用项目名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.129:3306/blue_sky_plan?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    enabled: true
  redis:
    host: 192.168.1.119
    port: 6379
  data:
    solr:
      host: http://127.0.0.1:8079/solr
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  config-locations: classpath:mybatis/confg.xml
