server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka #默认注册中心地址
  instance:
    lease-renewal-interval-in-seconds: 1     #表示eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，
    #server端没有收到client的心跳，则将摘除该instance
    lease-expiration-duration-in-seconds: 2 #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，
    #在这个时间内若没收到下一次心跳，则将移除该instance

spring:
  application:
    name: front-shopping-car-provider #应用名称  保证唯一   一般采用项目名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.156/blue_sky_plan?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: 123456        #数据库链接为本地 完善后改为远程

  redis:
    password:       # Redis服务器连接密码（默认为空）
    database: 0
    port: 6379
    pool:
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 0
      max-active: 200        # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1        # 连接池最大阻塞等待时间（使用负值表示没有限制）
    host: 192.168.0.24
    timeout: 1000

mybatis:
  type-aliases-package: org.bs.front.pojo
  mapper-locations: classpath:mybatis/*Mapper.xml


