server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: front-shopping-car-consumer

  redis:
    host: localhost #192.168.1.119
    port: 6380

  rabbitmq:
    host: 192.168.1.145   #x辛旭 的ip地址
    port: 5672
    username: rbdq
    password: 123456       #rabbitmq队列配置

  profiles: default
  freemarker:
    template-loader-path: classpath:/templates
    cache: true
    check-template-location: true
    content-type: text/html; charset=UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

  main:
    allow-bean-definition-overriding: true #允许写多个接口


feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 30000
